name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 8 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl https://data.sccgov.org/api/views/j2gj-bg6c/rows.csv?accessType=DOWNLOAD > data/$(date +%Y-%m-%d).csv
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push